module.exports = exports = {
    'root': true,

    'env': {
        'node': true
    },

    'extends': 'eslint:recommended',

    'rules': {
        'accessor-pairs': [ 'error', {
            'getWithoutSet': false,
            'setWithoutGet': true
        }],
        'arrow-body-style': [ 'error', 'always' ],
        'arrow-parens': [ 'error', 'always' ],
        'arrow-spacing': [ 'error', { 'before': true, 'after': true }],
        'block-scoped-var': 'warn',
        'callback-return': [ 'warn', [ 'callback', 'done', 'next' ]],
        'consistent-return': 'error',
        'constructor-super': 'error',
        'curly': 'error',
        'default-case': 'warn',
        'dot-location': [ 'warn', 'property' ],
        'dot-notation': 'warn',
        'eqeqeq': [ 'error', 'smart' ],
        'generator-star-spacing': [ 'error', 'before' ],
        'global-require': 'error',
        'guard-for-in': 'warn',
        'handle-callback-err': 'warn',
        'init-declarations': [ 'error', 'always' ],
        'no-alert': 'error',
        'no-caller': 'error',
        'no-case-declarations': 'warn',
        'no-catch-shadow': 'warn',
        'no-class-assign': 'error',
        'no-confusing-arrow': 'error',
        'no-const-assign': 'error',
        'no-constant-condition': 'error',
        'no-delete-var': 'error',
        'no-div-regex': 'warn',
        'no-dupe-class-members': 'error',
        'no-else-return': 'warn',
        'no-empty-pattern': 'warn',
        'no-eq-null': 'warn',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'warn',
        'no-extra-parens': 'error',
        'no-floating-decimal': 'warn',
        'no-implicit-coercion': [ 'warn', {
            'boolean': true,
            'number': true,
            'string': true
        }],
        'no-implied-eval': 'error',
        'no-invalid-this': 'error',
        'no-iterator': 'error',
        'no-label-var': 'error',
        'no-labels': [ 'warn', { allowLoop: true, allowSwitch: true } ],
        'no-lone-blocks': 'warn',
        'no-loop-func': 'error',
        'no-magic-numbers': 'off',
        'no-mixed-requires': 'warn',
        'no-multi-spaces': 'error',
        'no-multi-str': 'warn',
        'no-native-reassign': 'error',
        'no-new-func': 'error',
        'no-new-require': 'error',
        'no-new-wrappers': 'error',
        'no-new': 'error',
        'no-octal-escape': 'error',
        'no-param-reassign': 'error',
        'no-path-concat': 'error',
        'no-process-env': 'warn',
        'no-process-exit': 'error',
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-restricted-modules': 'off',
        'no-return-assign': 'error',
        'no-script-url': 'error',
        'no-self-compare': 'error',
        'no-shadow-restricted-names': 'error',
        'no-shadow': 'warn',
        'no-sync': 'warn',
        'no-this-before-super': 'error',
        'no-throw-literal': 'error',
        'no-undef-init': 'off',
        'no-undef': 'error',
        'no-undefined': 'off',
        'no-unexpected-multiline': 'error',
        'no-unused-expressions': 'error',
        'no-unused-vars': 'warn',
        'no-use-before-define': 'error',
        'no-useless-call': 'error',
        'no-useless-concat': 'error',
        'no-var': 'off',
        'no-void': 'warn',
        'no-warning-comments': [ 'warn', {
            'terms': [ 'TODO', 'FIXME' ],
            'location': 'start'
        }],
        'no-with': 'warn',
        'object-shorthand': [ 'warn', 'never' ],
        'prefer-arrow-callback': 'off',
        'prefer-spread': 'warn',
        'prefer-template': 'warn',
        'radix': 'warn',
        'require-yield': 'error',
        'strict': [ 'error', 'global' ],
        'vars-on-top': 'error',
        'wrap-iife': [ 'error', 'outside' ],
        'yoda': 'error',

        // Style
        'array-bracket-spacing': [ 'warn', 'always' ],
        'block-spacing': [ 'warn', 'always' ],
        'brace-style': [ 'warn', '1tbs', { 'allowSingleLine': false } ],
        'camelcase': 'warn',
        'comma-spacing': [ 'warn', { 'before': false, 'after': true } ],
        'comma-style': [ 'warn', 'last' ],
        'computed-property-spacing': [ 'warn', 'never' ],
        'consistent-this': [ 'warn', 'self' ],
        'eol-last': 'warn',
        'func-names': 'off',
        'func-style': [ 'warn', 'declaration' ],
        'id-length': [ 'warn', { 'min': 2, 'max': 32 } ],
        'indent': [ 'warn', 4 ],
        'jsx-quotes': [ 'warn', 'prefer-double' ],
        'keyword-spacing': [ 'warn', { before: true, after: true } ],
        'linebreak-style': 'off',
        'lines-around-comment': 'off',
        'max-depth': [ 'warn', 8 ],
        'max-len': [ 'warn', 132 ],
        'max-nested-callbacks': [ 'warn', 8 ],
        'max-params': [ 'warn', 8 ],
        'new-cap': 'warn',
        'new-parens': 'warn',
        'no-array-constructor': 'warn',
        'no-bitwise': 'off',
        'no-continue': 'off',
        'no-inline-comments': 'off',
        'no-lonely-if': 'warn',
        'no-mixed-spaces-and-tabs': 'warn',
        'no-multiple-empty-lines': 'warn',
        'no-negated-condition': 'off',
        'no-nested-ternary': 'warn',
        'no-new-object': 'warn',
        'no-plusplus': 'off',
        'no-spaced-func': 'warn',
        'no-ternary': 'off',
        'no-trailing-spaces': 'warn',
        'no-underscore-dangle': 'warn',
        'no-unneeded-ternary': 'warn',
        'object-curly-spacing': [ 'warn', 'always' ],
        'one-var': 'off',
        'operator-assignment': [ 'warn', 'never' ],
        'operator-linebreak': [ 'warn', 'after' ],
        'padded-blocks': [ 'warn', 'never' ],
        'quote-props': [ 'warn', 'consistent-as-needed' ],
        'quotes': [ 'warn', 'single' ],
        'semi-spacing': [ 'warn', { 'before': false, 'after': true }],
        'semi': [ 'error', 'always' ],
        'sort-vars': 'off',
        'space-before-blocks': [ 'warn', 'always' ],
        'space-before-function-paren': [ 'warn', { 'anonymous': 'always', 'named': 'never' } ],
        'space-in-parens': [ 'warn', 'never' ],
        'space-infix-ops': [ 'warn', { 'int32Hint': true } ],
        'space-unary-ops': 'error',
        'spaced-comment': [ 'warn', 'always' ],
        'wrap-regex': 'warn',

        // JSDoc Requirements
        'require-jsdoc': [ 'warn', {
            'require': {
                'FunctionDeclaration': true,
                'MethodDefinition': true,
                'ClassDeclaration': false
            }
        }],
        'valid-jsdoc': [ 'error', {
            'requireReturn': true,
            'requireReturnDescription': true,
            'requireParamDescription': true,
            'prefer': {
                'return': 'returns'
            }
        }]
    }
};
